<?php
echo "<table align=\"center\" width=\"98%\"  border=\"1\" cellpadding=\"5\" cellspacing=\"0\" bordercolor=\"#999999\">\n";
echo "<tr bgcolor=\"#FFCC99\">\n";
echo "<td rowspan=\"2\"><div align=\"center\">BIL</div></td>\n";
echo "<td rowspan=\"2\">Ujian/Peperiksaan</td>\n";
echo "<td rowspan=\"2\" align=\"center\">Bil. Murid</td>\n";
echo "<td colspan=\"2\"><div align=\"center\">A+</div></td>\n";
echo "<td colspan=\"2\"><div align=\"center\">A</div></td>\n";
echo "<td colspan=\"2\"><div align=\"center\">A-</div></td>\n";
echo "<td colspan=\"2\"><div align=\"center\">B+</div></td>\n";
echo "<td colspan=\"2\"><div align=\"center\">B</div></td>\n";
echo "<td colspan=\"2\"><div align=\"center\">C+</div></td>\n";
echo "<td colspan=\"2\"><div align=\"center\">C</div></td>\n";
echo "<td colspan=\"2\"><div align=\"center\">D</div></td>\n";
echo "<td colspan=\"2\"><div align=\"center\">E</div></td>\n";
echo "<td colspan=\"2\"><div align=\"center\">G</div></td>\n";
echo "<td rowspan=\"2\"><div align=\"center\">GP</div></td>\n";
echo "</tr>\n";
echo "<tr bgcolor=\"#FFCC99\">\n";
echo "<td><div align=\"center\">BIL</div></td>\n";
echo "<td><div align=\"center\">%</div></td>\n";
echo "<td><div align=\"center\">BIL</div></td>\n";
echo "<td><div align=\"center\">%</div></td>\n";
echo "<td><div align=\"center\">BIL</div></td>\n";
echo "<td><div align=\"center\">%</div></td>\n";
echo "<td><div align=\"center\">BIL</div></td>\n";
echo "<td><div align=\"center\">%</div></td>\n";
echo "<td><div align=\"center\">BIL</div></td>\n";
echo "<td><div align=\"center\">%</div></td>\n";
echo "<td><div align=\"center\">BIL</div></td>\n";
echo "<td><div align=\"center\">%</div></td>\n";
echo "<td><div align=\"center\">BIL</div></td>\n";
echo "<td><div align=\"center\">%</div></td>\n";
echo "<td><div align=\"center\">BIL</div></td>\n";
echo "<td><div align=\"center\">%</div></td>\n";
echo "<td><div align=\"center\">BIL</div></td>\n";
echo "<td><div align=\"center\">%</div></td>\n";
echo "<td><div align=\"center\">BIL</div></td>\n";
echo "<td><div align=\"center\">%</div></td>\n";
echo "</tr>\n";
//TOV
echo "<tr bgcolor='#CDCDCD'>\n";
echo "<td>1</td>\n";
echo "<td><div>TOV</div></td>\n";
echo "<td><div align=\"center\">$jumtov</div></td>\n";
echo "<td><div align=\"center\">$biltovAplus</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biltovAplus/($jumtov-$biltovTH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biltovA</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biltovA/($jumtov-$biltovTH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biltovAminus</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biltovAminus/($jumtov-$biltovTH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biltovBplus</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biltovBplus/($jumtov-$biltovTH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biltovB</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biltovB/($jumtov-$biltovTH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biltovCplus</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biltovCplus/($jumtov-$biltovTH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biltovC</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biltovC/($jumtov-$biltovTH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biltovD</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biltovD/($jumtov-$biltovTH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biltovE</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biltovE/($jumtov-$biltovTH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biltovG</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biltovG/($jumtov-$biltovTH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">".gpmpma($biltovAplus,$biltovA,$biltovAminus,$biltovBplus,$biltovB,$biltovCplus,$biltovC,$biltovD,$biltovE,$biltovG,$jumtov)."</div></td></tr>\n";
//UJIAN 1
echo "<tr>\n";
echo "<td>2</td>\n";
echo "<td><div>".jpep($jpepatr1)."</div></td>\n";
echo "<td><div align=\"center\">$jumatr1</div></td>\n";
echo "<td><div align=\"center\">$bilatr1Aplus</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr1Aplus/($jumatr1-$bilatr1TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$bilatr1A</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr1A/($jumatr1-$bilatr1TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$bilatr1Aminus</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr1Aminus/($jumatr1-$bilatr1TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$bilatr1Bplus</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr1Bplus/($jumatr1-$bilatr1TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$bilatr1B</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr1B/($jumatr1-$bilatr1TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$bilatr1Cplus</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr1Cplus/($jumatr1-$bilatr1TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$bilatr1C</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr1C/($jumatr1-$bilatr1TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$bilatr1D</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr1D/($jumatr1-$bilatr1TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$bilatr1E</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr1E/($jumatr1-$bilatr1TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$bilatr1G</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr1G/($jumatr1-$bilatr1TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">".gpmpma($bilatr1Aplus,$bilatr1A,$bilatr1Aminus,$bilatr1Bplus,$bilatr1B,$bilatr1Cplus,$bilatr1C,$bilatr1D,$bilatr1E,$bilatr1G,$jumatr1)."</div></td></tr>\n";
//OTI 1
echo "<tr bgcolor='#CDCDCD'>\n";
echo "<td>3</td>\n";
echo "<td><div>OTI1</div></td>\n";
echo "<td><div align=\"center\">$jumoti1</div></td>\n";
echo "<td><div align=\"center\">$biloti1Aplus</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biloti1Aplus/($jumoti1-$biloti1TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biloti1A</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biloti1A/($jumoti1-$biloti1TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biloti1Aminus</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biloti1Aminus/($jumoti1-$biloti1TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biloti1Bplus</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biloti1Bplus/($jumoti1-$biloti1TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biloti1B</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biloti1B/($jumoti1-$biloti1TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biloti1Cplus</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biloti1Cplus/($jumoti1-$biloti1TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biloti1C</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biloti1C/($jumoti1-$biloti1TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biloti1D</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biloti1D/($jumoti1-$biloti1TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biloti1E</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biloti1E/($jumoti1-$biloti1TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biloti1G</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biloti1G/($jumoti1-$biloti1TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">".gpmpma($biloti1Aplus,$biloti1A,$biloti1Aminus,$biloti1Bplus,$biloti1B,$biloti1Cplus,$biloti1C,$biloti1D,$biloti1E,$biloti1G,$jumoti1)."</div></td></tr>\n";
//PPT
echo "<tr>\n";
echo "<td>4</td>\n";
echo "<td><div>".jpep($jpepatr2)."</div></td>\n";
echo "<td><div align=\"center\">$jumatr2</div></td>\n";
echo "<td><div align=\"center\">$bilatr2Aplus</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr2Aplus/($jumatr2-$bilatr2TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$bilatr2A</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr2A/($jumatr2-$bilatr2TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$bilatr2Aminus</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr2Aminus/($jumatr2-$bilatr2TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$bilatr2Bplus</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr2Bplus/($jumatr2-$bilatr2TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$bilatr2B</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr2B/($jumatr2-$bilatr2TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$bilatr2Cplus</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr2Cplus/($jumatr2-$bilatr2TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$bilatr2C</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr2C/($jumatr2-$bilatr2TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$bilatr2D</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr2D/($jumatr2-$bilatr2TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$bilatr2E</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr2E/($jumatr2-$bilatr2TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$bilatr2G</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr2G/($jumatr2-$bilatr2TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">".gpmpma($bilatr2Aplus,$bilatr2A,$bilatr2Aminus,$bilatr2Bplus,$bilatr2B,$bilatr2Cplus,$bilatr2C,$bilatr2D,$bilatr2E,$bilatr2G,$jumatr2)."</div></td></tr>\n";
//OTI2
echo "<tr bgcolor='#CDCDCD'>\n";
echo "<td>5</td>\n";
echo "<td><div>OTI2</div></td>\n";
echo "<td><div align=\"center\">$jumoti2</div></td>\n";
echo "<td><div align=\"center\">$biloti2Aplus</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biloti2Aplus/($jumoti2-$biloti2TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biloti2A</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biloti2A/($jumoti2-$biloti2TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biloti2Aminus</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biloti2Aminus/($jumoti2-$biloti2TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biloti2Bplus</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biloti2Bplus/($jumoti2-$biloti2TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biloti2B</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biloti2B/($jumoti2-$biloti2TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biloti2Cplus</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biloti2Cplus/($jumoti2-$biloti2TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biloti2C</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biloti2C/($jumoti2-$biloti2TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biloti2D</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biloti2D/($jumoti2-$biloti2TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biloti2E</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biloti2E/($jumoti2-$biloti2TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biloti2G</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biloti2G/($jumoti2-$biloti2TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">".gpmpma($biloti2Aplus,$biloti2A,$biloti2Aminus,$biloti2Bplus,$biloti2B,$biloti2Cplus,$biloti2C,$biloti2D,$biloti2E,$biloti2G,$jumoti2)."</div></td></tr>\n";
//PERCUBAAN UPSR/PMR/PAT
echo "<tr>\n";
echo "<td>6</td>\n";
echo "<td><div>".jpep($jpepatr3)."</div></td>\n";
echo "<td><div align=\"center\">$jumatr3</div></td>\n";
echo "<td><div align=\"center\">$bilatr3Aplus</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr3Aplus/($jumatr3-$bilatr3TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$bilatr3A</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr3A/($jumatr3-$bilatr3TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$bilatr3Aminus</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr3Aminus/($jumatr3-$bilatr3TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$bilatr3Bplus</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr3Bplus/($jumatr3-$bilatr3TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$bilatr3B</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr3B/($jumatr3-$bilatr3TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$bilatr3Cplus</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr3Cplus/($jumatr3-$bilatr3TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$bilatr3C</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr3C/($jumatr3-$bilatr3TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$bilatr3D</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr3D/($jumatr3-$bilatr3TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$bilatr3E</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr3E/($jumatr3-$bilatr3TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$bilatr3G</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr3G/($jumatr3-$bilatr3TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">".gpmpma($bilatr3Aplus,$bilatr3A,$bilatr3Aminus,$bilatr3Bplus,$bilatr3B,$bilatr3Cplus,$bilatr3C,$bilatr3D,$bilatr3E,$bilatr3G,$jumatr3)."</div></td></tr>\n";
//SASARAN (ETR)
echo "<tr bgcolor='#CDCDCD'>\n";
echo "<td>7</td>\n";
echo "<td><div>SASARAN (ETR)</div></td>\n";
echo "<td><div align=\"center\">$jumetr</div></td>\n";
echo "<td><div align=\"center\">$biletrAplus</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biletrAplus/($jumetr-$biletrTH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biletrA</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biletrA/($jumetr-$biletrTH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biletrAminus</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biletrAminus/($jumetr-$biletrTH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biletrBplus</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biletrBplus/($jumetr-$biletrTH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biletrB</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biletrB/($jumetr-$biletrTH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biletrCplus</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biletrCplus/($jumetr-$biletrTH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biletrC</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biletrC/($jumetr-$biletrTH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biletrD</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biletrD/($jumetr-$biletrTH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biletrE</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biletrE/($jumetr-$biletrTH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biletrG</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biletrG/($jumetr-$biletrTH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">".gpmpma($biletrAplus,$biletrA,$biletrAminus,$biletrBplus,$biletrB,$biletrCplus,$biletrC,$biletrD,$biletrE,$biletrG,$jumetr)."</div></td></tr>\n";
echo "</table>\n";
?>