<?php
echo "<table align=\"center\" width=\"98%\"  border=\"1\" cellpadding=\"5\" cellspacing=\"0\" bordercolor=\"#999999\">\n";
echo "<tr bgcolor=\"#FFCC99\">\n";
echo "<td rowspan=\"2\"><div align=\"center\">BIL</div></td>\n";
echo "<td rowspan=\"2\">Ujian/Peperiksaan</td>\n";
echo "<td rowspan=\"2\" align=\"center\">Bil. Murid</td>\n";
echo "<td colspan=\"2\"><div align=\"center\">A</div></td>\n";
echo "<td colspan=\"2\"><div align=\"center\">B</div></td>\n";
echo "<td colspan=\"2\"><div align=\"center\">C</div></td>\n";
echo "<td colspan=\"2\"><div align=\"center\">D</div></td>\n";
echo "<td colspan=\"2\"><div align=\"center\">E</div></td>\n";
echo "<td rowspan=\"2\"><div align=\"center\">GP</div></td>\n";
echo "</tr>\n";
echo "<tr bgcolor=\"#FFCC99\">\n";
echo "<td><div align=\"center\">BIL</div></td>\n";
echo "<td><div align=\"center\">%</div></td>\n";
echo "<td><div align=\"center\">BIL</div></td>\n";
echo "<td><div align=\"center\">%</div></td>\n";
echo "<td><div align=\"center\">BIL</div></td>\n";
echo "<td><div align=\"center\">%</div></td>\n";
echo "<td><div align=\"center\">BIL</div></td>\n";
echo "<td><div align=\"center\">%</div></td>\n";
echo "<td><div align=\"center\">BIL</div></td>\n";
echo "<td><div align=\"center\">%</div></td>\n";
echo "</tr>\n";
echo "<tr bgcolor='#CDCDCD'>\n";
echo "<td>1</td>\n";
echo "<td><div>TOV</div></td>\n";
echo "<td><div align=\"center\">$jumtov</div></td>\n";
echo "<td><div align=\"center\">$biltovA</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biltovA/($jumtov-$biltovTH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biltovB</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biltovB/($jumtov-$biltovTH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biltovC</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biltovC/($jumtov-$biltovTH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biltovD</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biltovD/($jumtov-$biltovTH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biltovE</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biltovE/($jumtov-$biltovTH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">".gpmpmrsr($biltovA,$biltovB,$biltovC,$biltovD,$biltovE,$jumtov)."</div></td></tr>\n";
//UJIAN 1
echo "<tr>\n";
echo "<td>2</td>\n";
echo "<td><div>".jpep($jpepatr1)."</div></td>\n";
echo "<td><div align=\"center\">$jumatr1</div></td>\n";
echo "<td><div align=\"center\">$bilatr1A</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr1A/($jumatr1-$bilatr1TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$bilatr1B</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr1B/($jumatr1-$bilatr1TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$bilatr1C</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr1C/($jumatr1-$bilatr1TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$bilatr1D</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr1D/($jumatr1-$bilatr1TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$bilatr1E</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr1E/($jumatr1-$bilatr1TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">".gpmpmrsr($bilatr1A,$bilatr1B,$bilatr1C,$bilatr1D,$bilatr1E,$jumatr1)."</div></td></tr>\n";
//OTI 1
echo "<tr bgcolor='#CDCDCD'>\n";
echo "<td>3</td>\n";
echo "<td><div>OTI1</div></td>\n";
echo "<td><div align=\"center\">$jumoti1</div></td>\n";
echo "<td><div align=\"center\">$biloti1A</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biloti1A/($jumoti1-$biloti1TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biloti1B</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biloti1B/($jumoti1-$biloti1TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biloti1C</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biloti1C/($jumoti1-$biloti1TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biloti1D</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biloti1D/($jumoti1-$biloti1TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biloti1E</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biloti1E/($jumoti1-$biloti1TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">".gpmpmrsr($biloti1A,$biloti1B,$biloti1C,$biloti1D,$biloti1E,$jumoti1)."</div></td></tr>\n";
//PPT
echo "<tr>\n";
echo "<td>4</td>\n";
echo "<td><div>".jpep($jpepatr2)."</div></td>\n";
echo "<td><div align=\"center\">$jumatr2</div></td>\n";
echo "<td><div align=\"center\">$bilatr2A</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr2A/($jumatr2-$bilatr2TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$bilatr2B</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr2B/($jumatr2-$bilatr2TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$bilatr2C</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr2C/($jumatr2-$bilatr2TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$bilatr2D</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr2D/($jumatr2-$bilatr2TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$bilatr2E</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr2E/($jumatr2-$bilatr2TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">".gpmpmrsr($bilatr2A,$bilatr2B,$bilatr2C,$bilatr2D,$bilatr2E,$jumatr2)."</div></td></tr>\n";
//OTI2
echo "<tr bgcolor='#CDCDCD'>\n";
echo "<td>5</td>\n";
echo "<td><div>OTI2</div></td>\n";
echo "<td><div align=\"center\">$jumoti2</div></td>\n";
echo "<td><div align=\"center\">$biloti2A</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biloti2A/($jumoti2-$biloti2TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biloti2B</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biloti2B/($jumoti2-$biloti2TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biloti2C</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biloti2C/($jumoti2-$biloti2TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biloti2D</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biloti2D/($jumoti2-$biloti2TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biloti2E</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biloti2E/($jumoti2-$biloti2TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">".gpmpmrsr($biloti2A,$biloti2B,$biloti2C,$biloti2D,$biloti2E,$jumoti2)."</div></td></tr>\n";
//PERCUBAAN UPSR/PMR/PAT
echo "<tr>\n";
echo "<td>6</td>\n";
echo "<td><div>".jpep($jpepatr3)."</div></td>\n";
echo "<td><div align=\"center\">$jumatr3</div></td>\n";
echo "<td><div align=\"center\">$bilatr3A</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr3A/($jumatr3-$bilatr3TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$bilatr3B</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr3B/($jumatr3-$bilatr3TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$bilatr3C</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr3C/($jumatr3-$bilatr3TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$bilatr3D</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr3D/($jumatr3-$bilatr3TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$bilatr3E</div></td>\n";
echo "<td><div align=\"center\">".number_format(($bilatr3E/($jumatr3-$bilatr3TH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">".gpmpmrsr($bilatr3A,$bilatr3B,$bilatr3C,$bilatr3D,$bilatr3E,$jumatr3)."</div></td></tr>\n";
//SASARAN (ETR)
echo "<tr bgcolor='#CDCDCD'>\n";
echo "<td>7</td>\n";
echo "<td><div>SASARAN (ETR)</div></td>\n";
echo "<td><div align=\"center\">$jumetr</div></td>\n";
echo "<td><div align=\"center\">$biletrA</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biletrA/($jumetr-$biletrTH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biletrB</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biletrB/($jumetr-$biletrTH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biletrC</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biletrC/($jumetr-$biletrTH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biletrD</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biletrD/($jumetr-$biletrTH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">$biletrE</div></td>\n";
echo "<td><div align=\"center\">".number_format(($biletrE/($jumetr-$biletrTH))*100,2,'.',',')."</div></td>\n";
echo "<td><div align=\"center\">".gpmpmrsr($biletrA,$biletrB,$biletrC,$biletrD,$biletrE,$jumetr)."</div></td></tr>\n";
echo "</table>\n";
?>