<?php
echo "<table align=\"center\" width=\"98%\"  border=\"1\" cellpadding=\"5\" cellspacing=\"0\" bordercolor=\"#999999\">\n";
echo "<tr bgcolor=\"#FFCC99\">\n";
echo "<td rowspan=\"2\"><div align=\"center\">&nbsp;</div></td>\n";
echo "<td rowspan=\"2\" align=\"center\">HC</td>\n";
echo "<td rowspan=\"2\" align=\"center\">BIL. MURID</td>\n";
echo "<td colspan=\"7\"><div align=\"center\">BIL. DAPAT 'STRAIGHT' (A+|A|A-)</div></td>\n";
echo "<td rowspan=\"2\"><div align=\"center\">% DAPAT 'STRAIGHT' (A+|A|A-)</div></td>\n";
echo "</tr>\n";
echo "<tr bgcolor=\"#FFCC99\">\n";
echo "<td><div align=\"center\">12<br>(A+|A|A-)</div></td>\n";
echo "<td><div align=\"center\">11<br>(A+|A|A-)</div></td>\n";
echo "<td><div align=\"center\">10<br>(A+|A|A-)</div></td>\n";
echo "<td><div align=\"center\">9<br>(A+|A|A-)</div></td>\n";
echo "<td><div align=\"center\">8<br>(A+|A|A-)</div></td>\n";
echo "<td><div align=\"center\">7<br>(A+|A|A-)</div></td>\n";
echo "<td><div align=\"center\">JUM</div></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td rowspan=\"2\">MURID MENDAPAT SEMUA A DALAM SEMUA MATA PELAJARAN</td>";
echo "<td><div align=\"center\">TOV</div></td>\n";
echo "<td><div align=\"center\">$jumalltovA</div></td>\n";
echo "<td><div align=\"center\">$jumtov12AAll</div></td>\n";
echo "<td><div align=\"center\">$jumtov11AAll</div></td>\n";
echo "<td><div align=\"center\">$jumtov10AAll</div></td>\n";
echo "<td><div align=\"center\">$jumtov9AAll</div></td>\n";
echo "<td><div align=\"center\">$jumtov8AAll</div></td>\n";
echo "<td><div align=\"center\">$jumtov7AAll</div></td>\n";
echo "<td><div align=\"center\">$jumalltovA</div></td>\n";
echo "<td><div align=\"center\">".peratus($jumalltovA,$bilcalon)."</div></td></tr>\n";
echo "<td><div align=\"center\">ETR</div></td>\n";
echo "<td><div align=\"center\">$jumalletrA</div></td>\n";
echo "<td><div align=\"center\">$jumetr12AAll</div></td>\n";
echo "<td><div align=\"center\">$jumetr11AAll</div></td>\n";
echo "<td><div align=\"center\">$jumetr10AAll</div></td>\n";
echo "<td><div align=\"center\">$jumetr9AAll</div></td>\n";
echo "<td><div align=\"center\">$jumetr8AAll</div></td>\n";
echo "<td><div align=\"center\">$jumetr7AAll</div></td>\n";
echo "<td><div align=\"center\">$jumalletrA</div></td>\n";
echo "<td><div align=\"center\">".peratus($jumalletrA,$bilcalon)."</div></td></tr>\n";
echo "</table>\n";

echo "<br>";
echo "<table align=\"center\" width=\"98%\"  border=\"1\" cellpadding=\"5\" cellspacing=\"0\" bordercolor=\"#999999\">\n";
echo "<tr bgcolor=\"#FFCC99\">\n";
echo "<td><div align=\"center\">&nbsp;</div></td>\n";
echo "<td align=\"center\">HC</td>\n";
echo "<td align=\"center\">BIL. MURID</td>\n";
echo "<td><div align=\"center\">BIL. LULUS</div></td>\n";
echo "<td><div align=\"center\">% LULUS</div></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td rowspan=\"2\">MURID LULUS DALAM SEMUA MATA PELAJARAN</td>";
echo "<td><div align=\"center\">TOV</div></td>\n";
echo "<td><div align=\"center\">$bilcalon</div></td>\n";
echo "<td><div align=\"center\">$billulustov</div></td>\n";
echo "<td><div align=\"center\">".peratus($billulustov,$bilcalon)."</div></td></tr>\n";
//echo "<td><div align=\"center\">".peratus($jumalltovA,$bilcalon)."</div></td></tr>\n";
echo "<td><div align=\"center\">ETR</div></td>\n";
echo "<td><div align=\"center\">$bilcalon</div></td>\n";
echo "<td><div align=\"center\">$billulusetr</div></td>\n";
echo "<td><div align=\"center\">".peratus($billulusetr,$bilcalon)."</div></td></tr>\n";
//echo "<td><div align=\"center\">".peratus($jumalletrA,$bilcalon)."</div></td></tr>\n";
echo "</table>\n";
?>