<?php
echo "<table align=\"center\" width=\"98%\"  border=\"1\" cellpadding=\"5\" cellspacing=\"0\" bordercolor=\"#999999\">\n";
echo "<tr bgcolor=\"#FFCC99\">\n";
echo "<td rowspan=\"2\"><div align=\"center\">&nbsp;</div></td>\n";
echo "<td rowspan=\"2\" align=\"center\">HC</td>\n";
echo "<td rowspan=\"2\" align=\"center\">BIL. MURID</td>\n";
echo "<td colspan=\"4\"><div align=\"center\">BIL. DAPAT 'STRAIGHT' A</div></td>\n";
echo "<td rowspan=\"2\"><div align=\"center\">% DAPAT 'STRAIGHT' A</div></td>\n";
echo "</tr>\n";
echo "<tr bgcolor=\"#FFCC99\">\n";
echo "<td><div align=\"center\">7A</div></td>\n";
echo "<td><div align=\"center\">6A</div></td>\n";
echo "<td><div align=\"center\">5A</div></td>\n";
echo "<td><div align=\"center\">JUM</div></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td rowspan=\"2\">MURID MENDAPAT SEMUA A DALAM SEMUA MATA PELAJARAN</td>";
echo "<td><div align=\"center\">TOV</div></td>\n";
echo "<td><div align=\"center\">$jumalltovA</div></td>\n";
echo "<td><div align=\"center\">$jumtov7A</div></td>\n";
echo "<td><div align=\"center\">$jumtov6A</div></td>\n";
echo "<td><div align=\"center\">$jumtov5A</div></td>\n";
echo "<td><div align=\"center\">$jumalltovA</div></td>\n";
echo "<td><div align=\"center\">".peratus($jumalltovA,$bilcalon)."</div></td></tr>\n";
echo "<td><div align=\"center\">ETR</div></td>\n";
echo "<td><div align=\"center\">$jumalletrA</div></td>\n";
echo "<td><div align=\"center\">$jumetr7A</div></td>\n";
echo "<td><div align=\"center\">$jumetr6A</div></td>\n";
echo "<td><div align=\"center\">$jumetr5A</div></td>\n";
echo "<td><div align=\"center\">$jumalletrA</div></td>\n";
echo "<td><div align=\"center\">".peratus($jumalletrA,$bilcalon)."</div></td></tr>\n";
echo "</table>\n";

echo "<br>";
echo "<table align=\"center\" width=\"98%\"  border=\"1\" cellpadding=\"5\" cellspacing=\"0\" bordercolor=\"#999999\">\n";
echo "<tr bgcolor=\"#FFCC99\">\n";
echo "<td><div align=\"center\">&nbsp;</div></td>\n";
echo "<td align=\"center\">HC</td>\n";
echo "<td align=\"center\">BIL. MURID</td>\n";
echo "<td><div align=\"center\">BIL. LULUS</div></td>\n";
echo "<td><div align=\"center\">% LULUS</div></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td rowspan=\"2\">MURID LULUS DALAM SEMUA MATA PELAJARAN</td>";
echo "<td><div align=\"center\">TOV</div></td>\n";
echo "<td><div align=\"center\">$bilcalon</div></td>\n";
echo "<td><div align=\"center\">$billulustov</div></td>\n";
echo "<td><div align=\"center\">".peratus($billulustov,$bilcalon)."</div></td></tr>\n";
//echo "<td><div align=\"center\">".peratus($jumalltovA,$bilcalon)."</div></td></tr>\n";
echo "<td><div align=\"center\">ETR</div></td>\n";
echo "<td><div align=\"center\">$bilcalon</div></td>\n";
echo "<td><div align=\"center\">$billulusetr</div></td>\n";
echo "<td><div align=\"center\">".peratus($billulusetr,$bilcalon)."</div></td></tr>\n";
//echo "<td><div align=\"center\">".peratus($jumalletrA,$bilcalon)."</div></td></tr>\n";
echo "</table>\n";
?>